package com.easydatalink.tech.orm;

import java.util.List;

import com.easydatalink.tech.entity.IdEntity;

public interface Mapper<T extends IdEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_methodlog
     *
     * @mbggenerated Mon Apr 02 15:31:36 CST 2012
     */
    int deleteByPrimaryKey(Long id);

    public T getByCode(final String code);
    
    public T getByCode(T entity);
    
    public T getCityCode(T entity);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_methodlog
     *
     * @mbggenerated Mon Apr 02 15:31:36 CST 2012
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_methodlog
     *
     * @mbggenerated Mon Apr 02 15:31:36 CST 2012
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_methodlog
     *
     * @mbggenerated Mon Apr 02 15:31:36 CST 2012
     */
    T selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_methodlog
     *
     * @mbggenerated Mon Apr 02 15:31:36 CST 2012
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_methodlog
     *
     * @mbggenerated Mon Apr 02 15:31:36 CST 2012
     */
    int updateByPrimaryKey(T record);
    
    List<T> getAll();
    
    void deleteAll();
}