package com.easydatalink.tech.mapper.base;

import com.easydatalink.tech.entity.base.SystemLog;
import com.easydatalink.tech.orm.Mapper;

public interface SystemLogMapper extends Mapper<SystemLog>{
    int insertSelective(SystemLog record);
    int updateByPrimaryKeySelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_log
     *
     * @mbggenerated Wed May 24 16:29:10 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(SystemLog record);
}